import { INestApplication } from '@nestjs/common';
import metadata from './metadata'; // <-- file auto-generated by the "PluginMetadataGenerator"
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';

export class SwaggerService {
  static async createService(app: INestApplication) {
    const config = new DocumentBuilder()
      .setTitle('Example API')
      .setDescription('The example API description')
      .setVersion('1.0')
      .build();
    await SwaggerModule.loadPluginMetadata(metadata); // <-- here
    const document = SwaggerModule.createDocument(app, config);
    SwaggerModule.setup('api', app, document);
  }
}
